/**
 * Generate `public/.htaccess` — the site's redirect and gone map.
 *
 * Every rule traces back to the URL inventory in `data/live-urls.txt`. Each
 * address the WordPress site answered is served by a built page, redirected
 * once to a page that exists, or returned as `410 Gone` on purpose. Nothing is
 * left to 404. See docs/urls.md.
 *
 * **This site is the easy case, and it is worth knowing why.** WordPress served
 * posts at `/blog/<slug>/` and `/talks/<slug>/` and training at
 * `/training/<slug>/`, and the rebuild keeps all three. So the bulk of the
 * inventory needs no rule at all — only the WordPress *machinery* does: the
 * feeds, the pagination, the category and tag archives, the author page.
 *
 * Run: `npm run redirects` (writes public/.htaccess)
 *
 * The output is committed and a test fails if it is not what this script would
 * write today. Never edit `public/.htaccess`; edit this.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { site } from '../site.config.ts';

const host = new URL(site.url).host;

/** Escape a path for use inside a RewriteRule pattern. */
const esc = (p: string) => p.replace(/[.?*+^$[\]\\(){}|]/g, '\\$&');

const L: string[] = [];
const section = (title: string) =>
  L.push('', `# --- ${title} ${'-'.repeat(Math.max(0, 62 - title.length))}`);

// ---------------------------------------------------------------------------
// The decisions. Everything below this block is mechanical.
// ---------------------------------------------------------------------------

/**
 * WordPress pages that the rebuild does not serve at the same address.
 *
 * Empty today, and that is the point: the rebuild deliberately keeps every
 * page path WordPress used. Add a line here only when a page genuinely moves,
 * and prefer not moving it.
 */
const MOVED: Record<string, string> = {};

/**
 * The single `project` custom post type. It is a duplicate of the talk of the
 * same name — the CPT was used once in 2023 and then abandoned — so its two
 * addresses point at the talk rather than being retired. A duplicate is not
 * the same thing as a mistake: somebody may have linked to it.
 */
const PROJECTS: Record<string, string> = {
  'facilitating-collaborative-design-decisions': '/talks/facilitating-collaborative-design-decisions/',
};

/**
 * Pages that exist on WordPress and are deliberately not rebuilt.
 *
 * `410 Gone` rather than a redirect to the home page, so search engines drop
 * them cleanly instead of showing a soft 404 for years. A redirect to `/` is
 * the tempting alternative and it is worse: it tells a crawler the home page
 * *is* that content.
 *
 * Empty until the content review in MIGRATION.md phase 3 decides which of the
 * 2017–2019 posts are worth carrying over. Anything dropped there gets a line
 * here, not silence.
 */
const GONE_PAGES: string[] = [];

/**
 * Editorial changes in Notion that retire a URL: a merged duplicate, or a
 * renamed slug. Notion is the source of truth, so the page simply stops
 * existing on the next sync — this is where its old URL keeps working. Add a
 * line here whenever `npm run check:urls` reports a slug with no page.
 */
const RETIRED: Record<string, string> = {};

/**
 * Rules the sync recorded for itself: a slug renamed in Notion, or a page
 * deliberately retired there. The run that breaks a URL is the run that keeps
 * the promise, so the sync writes here rather than leaving it to be noticed.
 */
function recordedRules(): { from: string; kind: string; to: string }[] {
  let text = '';
  try {
    text = readFileSync('data/retired-urls.csv', 'utf8');
  } catch {
    return []; // nothing has been retired yet
  }
  return text
    .trim()
    .split('\n')
    .slice(1)
    .filter(Boolean)
    .map((line) => {
      const [from, kind, to] = line.split(',');
      return { from, kind, to };
    });
}

/** Slugs the build actually produces, so a rule can be checked against reality. */
function slugsIn(collection: string): Set<string> {
  try {
    return new Set(
      readdirSync(`src/content/${collection}`)
        .filter((f) => f.endsWith('.md'))
        .map((f) => f.replace(/\.md$/, '')),
    );
  } catch {
    return new Set(); // the collection has not been synced yet
  }
}

const inventory = readFileSync('data/live-urls.txt', 'utf8').trim().split('\n');

// ---------------------------------------------------------------------------

L.push('# Generated by scripts/build-redirects.ts — do not edit by hand.');
L.push(`# The URL contract: ${inventory.length} addresses, each served, redirected once, or Gone.`);
L.push('# The inventory is data/live-urls.txt. See docs/urls.md.');
L.push('');

// Branded error pages. Without these the host serves its own: an unbranded 404
// with no way back into the site, and — for the addresses retired on purpose —
// a bare "Gone" that tells a person nothing.
L.push('ErrorDocument 404 /404.html');
// Astro special-cases 404.astro into dist/404.html; every other page, this one
// included, is a directory with an index.html.
L.push('ErrorDocument 410 /410/');
L.push('');

// Every content page also ships its own markdown (see src/lib/markdown-page.ts).
// LiteSpeed would otherwise send .md as application/octet-stream, which makes a
// browser download the file instead of showing it — and tells a crawler nothing
// about what it is.
L.push('<IfModule mod_mime.c>');
L.push('AddType text/markdown .md');
L.push('AddCharset UTF-8 .md');
L.push('</IfModule>');
L.push('');

L.push('<IfModule mod_rewrite.c>');
L.push('RewriteEngine On');

section('0. One hostname');
// WordPress sent www to the bare domain; a static site does not, so without
// this both hostnames answer 200 with the same pages after the cutover.
//
// First, so a www request is normalised before any path rule sees it, and
// absolute because the host is the part being changed. Every address in the
// inventory is a bare-domain one, so nothing in the URL contract goes through
// here — check-redirects.mjs skips host-conditional rules for that reason.
L.push(`RewriteCond %{HTTP_HOST} ^www\\.${esc(host)}$ [NC]`);
L.push(`RewriteRule ^(.*)$ ${site.url}/$1 [R=301,L]`);

section('1. Feeds');
// Yoast published a feed per archive. Subscribers to any of them are real, and
// they all want the same thing now: one feed of everything published.
L.push('RewriteRule ^feed/?$ /rss.xml [R=301,L]');
L.push('RewriteRule ^(blog|talks|training)/feed/?$ /rss.xml [R=301,L]');
L.push('RewriteRule ^comments/feed/?$ /rss.xml [R=301,L]');

section('2. Pagination');
// WordPress paginated every archive. The rebuilt indexes are one page with a
// filter and a "load more", so page 2 of anything is the index itself. The
// pattern is open-ended because `/blog/page/9/` is as linkable as `/page/2/`.
L.push('RewriteRule ^page/[0-9]+/?$ / [R=301,L]');
L.push('RewriteRule ^(blog|talks|training)/page/[0-9]+/?$ /$1/ [R=301,L]');

section('3. Category archives');
// Two categories, and they *are* the two sections. `/category/blog/` and
// `/blog/` listed the same posts, which is why this is a redirect and not a
// page: it was duplicate content on WordPress too.
L.push('RewriteRule ^category/blog/?$ /blog/ [R=301,L]');
L.push('RewriteRule ^category/talks/?$ /talks/ [R=301,L]');
L.push('# Any other category archive was never a page anyone linked to.');
L.push('RewriteRule ^category/ - [G,L]');

section('4. Tag archives → the filtered index');
// 57 tags, each with its own WordPress archive. The rebuilt index reads `?tag=`
// and pre-selects it (src/lib/filter-url.ts); an unknown tag shows the full
// archive rather than an error, so a tag renamed in Notion degrades to a
// useful page instead of a dead one.
//
// QSA so an existing query string survives. These are deliberately *not*
// disallowed in robots.txt: blocking the destination would throw away the
// redirect. Every index canonicalises to its clean path instead, so the
// filtered views consolidate into it rather than competing with it.
L.push('RewriteRule ^tag/([^/]+)/?$ /blog/?tag=$1 [R=301,L,QSA]');

section('5. Author archives — Gone');
// One author, so an author archive is the whole blog with a different address.
// WordPress already 404s `/author/kenny/`; only `/author/admin-2/` is in the
// inventory, and it is a default-username artefact nobody meant to publish.
L.push('RewriteRule ^author/ - [G,L]');

section('6. The `project` custom post type');
for (const [from, to] of Object.entries(PROJECTS)) {
  L.push(`RewriteRule ^project/${esc(from)}/?$ ${to} [R=301,L]`);
}
L.push('RewriteRule ^project/?$ /talks/ [R=301,L]');

section('7. WordPress machinery — Gone');
// Addresses that only ever existed because the site ran WordPress. They are in
// the inventory because they answered 200, not because anyone wanted them.
for (const p of ['wp-json', 'wp-content/plugins', 'xmlrpc.php', 'wp-login.php']) {
  L.push(`RewriteRule ^${esc(p)} - [G,L]`);
}
L.push('# wp-content/uploads is deliberately absent: the parked WordPress');
L.push('# directory still serves the media those addresses point at, and things');
L.push('# outside this repository still reference them. See docs/operations.md.');

if (Object.keys(MOVED).length) {
  section('8. Pages that moved');
  for (const [from, to] of Object.entries(MOVED)) {
    L.push(`RewriteRule ^${esc(from.slice(1))}?$ ${to} [R=301,L]`);
  }
}

if (GONE_PAGES.length) {
  section('9. Content deliberately not carried over — Gone');
  for (const p of GONE_PAGES) {
    L.push(`RewriteRule ^${esc(p.slice(1))}?$ - [G,L]`);
  }
}

section('10. Retired slugs (editorial merges and renames)');
L.push('# Content that moved after the URL inventory was taken: the old address');
L.push('# keeps working. The hand-written ones first, then whatever the sync');
L.push('# recorded when a slug changed or a page was retired in Notion.');
for (const [from, to] of Object.entries(RETIRED)) {
  L.push(`RewriteRule ^${esc(from.slice(1))}?$ ${to} [R=301,L]`);
}
for (const r of recordedRules()) {
  if (Object.hasOwn(RETIRED, r.from)) continue; // a hand-written rule wins
  L.push(
    r.kind === '410'
      ? `RewriteRule ^${esc(r.from.slice(1))}?$ - [G,L]`
      : `RewriteRule ^${esc(r.from.slice(1))}?$ ${r.to} [R=301,L]`,
  );
}

L.push('</IfModule>');
L.push('');

// `--out=` lets the test regenerate somewhere harmless and compare, rather than
// overwriting the file it is checking.
const out = process.argv.find((a) => a.startsWith('--out='))?.slice(6) ?? 'public/.htaccess';
writeFileSync(out, L.join('\n'));

const rules = L.filter((l) => l.startsWith('RewriteRule')).length;
const built = site.sections
  .filter((s) => 'collection' in s && s.collection)
  .map((s) => `${s.path} ${slugsIn((s as { collection: string }).collection).size}`)
  .join(' · ');
console.log(`build-redirects: ${rules} rules -> ${out}`);
console.log(`  inventory ${inventory.length} addresses · built pages: ${built || 'none synced yet'}`);
